FROM golang:1.24.2

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application
COPY . .

# Build the application
RUN go build -o xops-admin

EXPOSE 8005

CMD ["./xops-admin"]